services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql:v1
  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    image: mongo:v1
  rabbit:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    image: rabbit:v1
  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    image: catalogue:v1
  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    image: cart:v1
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: user:v1
  shipping:
    build:
      context: ./shipping
      dockerfile: Dockerfile
    image: shipping:v1
  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    image: payment:v1
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:v1

  
  
  
